MAKEFLAGS += --silent

restore:
	dotnet restore --interactive
build:
	dotnet build
run:
	dotnet run --no-build -- --endpoint "https://basicaccountjqqa.services.ai.azure.com/api/projects/e2e-tests/" --apiVersion "2025-05-15-preview"